//! `satex-core` — the shared kernel of the SATEX Rust engine (RS-UP-1 / RS-1.1).
//!
//! This crate holds the primitives every other engine crate depends on and nothing
//! else: the time newtype ([`UtcMillis`]), data-point provenance ([`Provenance`],
//! [`Source`], [`SideProvenance`]), the [`Symbol`] newtype, the injected [`Clock`]
//! and [`SeededRng`] traits (the determinism spine from
//! `docs/plans/rs-clock-rng-injection-design.md`), id generation ([`IdGen`]), and the
//! shared [`CoreError`] taxonomy.
//!
//! ## Governing laws (read before editing)
//!
//! - **Port behavior, not intentions (RS-L1).** Every value ported from the TypeScript
//!   engine is pinned against the TS source at `file:line`; the reference vectors in
//!   [`rng`] were generated by running the *actual* `services/rng.ts` under node.
//! - **Numeric law (Appendix B).** All engine math is `f64`; `f32` is denied by lint.
//!   Ported arithmetic preserves TS expression and accumulation order verbatim.
//! - **Determinism (RS-0.6/0.7).** Wall-clock and randomness are reached only through
//!   [`Clock`] and [`SeededRng`]; the single sanctioned `SystemTime::now` read lives in
//!   [`clock::SystemClock`].
//!
//! Merging this crate changes nothing user-visible — it is an unshipped additive
//! sibling of the Electron engine until the audited M5 flip.

#![forbid(unsafe_code)]
#![deny(missing_docs)]

pub mod clock;
pub mod error;
pub mod ids;
pub mod provenance;
pub mod rng;
pub mod symbol;
pub mod time;

pub use clock::{Clock, FixedClock, SteppedClock, SystemClock};
pub use error::CoreError;
pub use ids::IdGen;
pub use provenance::{Provenance, SideProvenance, Source};
pub use rng::{Mulberry32, SeededRng};
pub use symbol::{Symbol, is_known_crypto_ticker};
pub use time::UtcMillis;
