//! [`SeededRng`] and [`Mulberry32`] — the deterministic PRNG, a bit-exact port of the
//! TS simulator's `services/rng.ts`.
//!
//! Randomness is injected exactly like the clock (RS-0.7). [`Mulberry32`] is a
//! character-for-character port of the TS `mulberry32` — same 32-bit integer ops
//! (`wrapping_*` reproduces JS `| 0` / `>>> 0` / `Math.imul`), same `f64` division,
//! same Box–Muller with the identical spare-caching. The reference vectors in the
//! tests were produced by running the *actual* TS source under node
//! (`scratchpad/gen-rng-vectors.mjs`, which pastes `rng.ts`'s body verbatim), so this
//! is parity *measured*, not asserted (RS-L4, Appendix B).
//!
//! ## Bit-exactness scope (an honest boundary)
//! [`Mulberry32::next_f64`] is integer-derived and therefore **bit-exact** across
//! engines — the tests assert the raw `f64` bit patterns. [`Mulberry32::next_gaussian`]
//! depends on `f64::ln`, which IEEE-754 does **not** mandate to be correctly-rounded,
//! so a last-ULP divergence between V8's `Math.log` and Rust's `std` is possible.
//! `sqrt` is IEEE-mandated exact. The gaussian tests therefore assert a tight relative
//! tolerance and this boundary is logged for the parity harness (RS-2.x / RS-3.1): if
//! the simulator's gaussian stream ever drifts, the first divergent draw is the place
//! to look, and the resolution is a ledgered numeric ruling — never a silent tolerance
//! widening.

/// A deterministic, seedable PRNG. `Send` so it can move into a worker task; not
/// `Sync` because draws mutate internal state (`&mut self`).
pub trait SeededRng: Send {
    /// Next uniform draw in `[0, 1)`. Bit-exact port target.
    fn next_f64(&mut self) -> f64;
    /// Next standard-normal draw (Box–Muller). See the module's bit-exactness note.
    fn next_gaussian(&mut self) -> f64;
    /// Next integer in `[0, max)` — `Math.floor(next() * max)`, faithful to `nextInt`.
    fn next_int(&mut self, max: u64) -> u64;
}

/// The `mulberry32` PRNG (32-bit state), bit-exact with `services/rng.ts`.
#[derive(Debug, Clone)]
pub struct Mulberry32 {
    state: u32,
    /// Box–Muller caches the second normal draw here, matching TS `_spare`.
    spare: Option<f64>,
}

impl Mulberry32 {
    /// Seeds the generator. In TS the seed is `seed >>> 0`; a `u32` is already that.
    #[must_use]
    pub const fn from_seed(seed: u32) -> Self {
        Self {
            state: seed,
            spare: None,
        }
    }
}

impl SeededRng for Mulberry32 {
    fn next_f64(&mut self) -> f64 {
        // TS:  s |= 0; s = s + 0x6D2B79F5 | 0
        // `| 0` is a 32-bit coercion (no-op on our u32); the add wraps mod 2^32.
        self.state = self.state.wrapping_add(0x6D2B_79F5);
        let s = self.state;
        // TS:  let t = Math.imul(s ^ (s >>> 15), 1 | s)
        let mut t = (s ^ (s >> 15)).wrapping_mul(1 | s);
        // TS:  t = t + Math.imul(t ^ (t >>> 7), 61 | t) ^ t
        //      ('+' binds tighter than '^' in JS, so: (t + imul(...)) ^ t)
        let imul = (t ^ (t >> 7)).wrapping_mul(61 | t);
        t = t.wrapping_add(imul) ^ t;
        // TS:  return ((t ^ (t >>> 14)) >>> 0) / 4294967296
        f64::from(t ^ (t >> 14)) / 4_294_967_296.0
    }

    fn next_gaussian(&mut self) -> f64 {
        if let Some(v) = self.spare.take() {
            return v;
        }
        // TS Marsaglia polar: reject outside the unit circle (and the origin).
        let (u, v, s) = loop {
            let u = self.next_f64() * 2.0 - 1.0;
            let v = self.next_f64() * 2.0 - 1.0;
            let s = u * u + v * v;
            if !(s >= 1.0 || s == 0.0) {
                break (u, v, s);
            }
        };
        // TS:  const mul = Math.sqrt(-2 * Math.log(s) / s)
        let mul = (-2.0 * s.ln() / s).sqrt();
        self.spare = Some(v * mul);
        u * mul
    }

    fn next_int(&mut self, max: u64) -> u64 {
        // TS:  Math.floor(next() * max)
        let scaled = (self.next_f64() * (max as f64)).floor();
        // scaled is in [0, max); non-negative and below 2^53 for realistic max.
        scaled as u64
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // Reference vectors — generated by node from the verbatim TS rng.ts body
    // (scratchpad/gen-rng-vectors.mjs, 2026-07-25). Do NOT hand-edit; regenerate.

    #[test]
    fn next_f64_matches_ts_decimal_vectors() {
        let cases: [(u32, [f64; 8]); 3] = [
            (
                0,
                [
                    0.266_429_208_684_712_65,
                    0.000_329_745_700_582_861_9,
                    0.223_272_027_447_819_7,
                    0.146_202_147_938_311_1,
                    0.467_327_822_931_110_86,
                    0.545_049_082_720_652_2,
                    0.615_251_384_442_672_1,
                    0.648_985_379_841_178_7,
                ],
            ),
            (
                1,
                [
                    0.627_073_940_588_161_3,
                    0.002_735_721_180_215_478,
                    0.527_447_039_959_952_2,
                    0.981_050_967_471_674_1,
                    0.968_377_898_214_384_9,
                    0.281_103_502_959_013,
                    0.612_838_860_601_186_8,
                    0.720_743_141_137_063_5,
                ],
            ),
            (
                12345,
                [
                    0.979_728_267_760_947_3,
                    0.306_752_264_499_664_3,
                    0.484_205_421_525_985,
                    0.817_934_412_509_203,
                    0.509_428_369_347_006_1,
                    0.347_471_860_470_250_25,
                    0.073_757_541_831_582_78,
                    0.766_396_467_341_110_1,
                ],
            ),
        ];
        for (seed, expected) in cases {
            let mut r = Mulberry32::from_seed(seed);
            for (i, want) in expected.iter().enumerate() {
                let got = r.next_f64();
                assert_eq!(got, *want, "seed {seed} draw {i}: {got} != {want}");
            }
        }
    }

    #[test]
    fn next_f64_is_bit_exact_with_v8() {
        // Raw IEEE-754 bit patterns — the strongest possible parity assertion.
        let cases: [(u32, [u64; 8]); 2] = [
            (
                1,
                [
                    0x3fe4_10fd_5e60_0000,
                    0x3f66_6939_2000_0000,
                    0x3fe0_e0d8_9d60_0000,
                    0x3fef_64c4_ffa0_0000,
                    0x3fee_fcf3_a560_0000,
                    0x3fd1_fd99_8c00_0000,
                    0x3fe3_9c60_3e00_0000,
                    0x3fe7_1053_eb80_0000,
                ],
            ),
            (
                12345,
                [
                    0x3fef_59ef_18a0_0000,
                    0x3fd3_a1d4_4000_0000,
                    0x3fde_fd38_bc80_0000,
                    0x3fea_2c84_ca00_0000,
                    0x3fe0_4d3c_b940_0000,
                    0x3fd6_3cfa_9d40_0000,
                    0x3fb2_e1c6_3600_0000,
                    0x3fe8_8651_e260_0000,
                ],
            ),
        ];
        for (seed, bits) in cases {
            let mut r = Mulberry32::from_seed(seed);
            for (i, want) in bits.iter().enumerate() {
                let got = r.next_f64().to_bits();
                assert_eq!(
                    got, *want,
                    "seed {seed} draw {i}: {got:#018x} != {want:#018x}"
                );
            }
        }
    }

    #[test]
    fn next_int_matches_ts_vectors() {
        let cases: [(u32, [u64; 6]); 2] = [
            (1, [627, 2, 527, 981, 968, 281]),
            (12345, [979, 306, 484, 817, 509, 347]),
        ];
        for (seed, expected) in cases {
            let mut r = Mulberry32::from_seed(seed);
            for (i, want) in expected.iter().enumerate() {
                assert_eq!(r.next_int(1000), *want, "seed {seed} int {i}");
            }
        }
    }

    #[test]
    fn next_gaussian_matches_ts_within_tolerance() {
        // Tight relative tolerance; the ln-dependent last-ULP boundary is documented.
        let cases: [(u32, [f64; 6]); 2] = [
            (
                1,
                [
                    0.021_917_298_522_725_42,
                    0.384_133_869_229_842_66,
                    0.762_459_696_967_142_7,
                    1.491_576_107_754_233_3,
                    -2.995_074_719_413_300_3,
                    -0.750_741_633_345_216_7,
                ],
            ),
            (
                12345,
                [
                    -0.066_682_027_887_465_47,
                    1.342_265_094_076_577_2,
                    0.134_342_113_240_455_2,
                    -2.173_329_431_517_059,
                    -0.059_535_764_572_703_244,
                    0.662_513_183_337_021_7,
                ],
            ),
        ];
        for (seed, expected) in cases {
            let mut r = Mulberry32::from_seed(seed);
            for (i, want) in expected.iter().enumerate() {
                let got = r.next_gaussian();
                let tol = 1e-9 * (1.0 + want.abs());
                assert!(
                    (got - want).abs() < tol,
                    "seed {seed} gauss {i}: {got} vs {want} (|Δ|={})",
                    (got - want).abs()
                );
            }
        }
    }

    #[test]
    fn gaussian_spare_alternation_is_stable() {
        // Two fresh generators with the same seed must agree draw-for-draw (the spare
        // cache is internal state, not global) — regression pin for the P-061 aliasing
        // class carried into the RNG.
        let mut a = Mulberry32::from_seed(777);
        let mut b = Mulberry32::from_seed(777);
        for _ in 0..10 {
            assert_eq!(a.next_gaussian().to_bits(), b.next_gaussian().to_bits());
        }
    }

    #[test]
    fn next_int_zero_max_is_zero() {
        // Math.floor(x * 0) === 0 for any finite x — degenerate guard.
        let mut r = Mulberry32::from_seed(5);
        assert_eq!(r.next_int(0), 0);
    }
}
